config/routes.rb
Rails.application.routes.draw do
resources :orders do
  get 'myorder', :on => :collection
end
  resources :products
  get 'customer/index'
    get 'products/index'
  resources :customer
    root 'home#index'
      resources :carts
    devise_for :users
    devise_scope :user do  
      get '/users/sign_out' => 'devise/sessions#destroy'     
   end
    resources :products
      get 'mydashbord', to: "products#mydashbord"
      post 'search', to: "customer#search"
      post 'searchp', to: "products#searchp"


      namespace :api do
        namespace :v1 ,defaults: {format: :json} do
        resources :seller
        resources :sessions, only: [:create,:destroy]
       
        end
      end
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  load_and_authorize_resource :class =>"Cart"
  layout "customer_layout"
  def index
    @user=current_user
    @products=Product.all
    
    
  end
  def show
    @product=Product.find(params[:id])
  end
  def search
    keyword=params[:query]
    @products=Product.where('products.name LIKE ?',"%#{keyword}%")
  end
 
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customer/_form.html.erb
<div style="font-size:20px; padding:10px; font-weight:bold;">
    <tr>
      <th>Product_Name
      </th>
      <th>| Price</th>
      <th>| Peller_name</th>
      <th>| Stoke Available</th>
      <th>| Select Quantity</th>
      <th colspan="5"></th>
    </tr>
    </div>
  
    
<% @products.each do |product| %>
 
   <%=form_with model: product, url:carts_path, method: :post do |form| %>
  <tr> 
   <%var=User.find(product.user_id)%>
        <td><%=product.id%></td>  
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%=var.name%></td>
        <% if product.quantity.nil? ||product.quantity==0%>
        <td><strong>out of Stock</strong></td>
        <td><%= link_to 'GO TO cart',carts_path%></td>
        <%else%>
        <td><%= product.quantity %></td>
        <td><%= form.hidden_field :product_id,value: product.id %></td>
        <td><%= form.hidden_field :sell_id,value: product.user_id %></td>
        <td><%= form.hidden_field :pro_name,value: product.name %></td>
        <td><%= form.hidden_field :pro_price,value: product.price %></td>
        <td><%= form.hidden_field :subtotal,value: 0 %></td>
      
        <td><%=form.number_field 'pro_quantity', min: 1, max: product.quantity, step: 1%></td>
        <td><%= link_to 'Viwe', customer_path(product) %></td>
        <td><%=form.submit "ADD TO CART"%></td>
         <%end%>
      </tr>
   <%end%>
<%end%>

<br>
<h1><%= link_to 'my cart',carts_path%></h1>
<h1><%= link_to 'my Order',myorder_orders_path%></h1>

app/views/customer/index.html copy.erb
   <!--
  <div class="bg-info" style="margin:30px 380px;padding:10px 20px 5px 20px;text-align:center;">
<h1>Products</h1>
</div>-->

<div >
<%= image_tag "ban1.jpg",style:"height:600px;width:1254px; position:absolute;left:15px;top:75px;z-index:-1;"%>
<div style="margin-top:253px;">
<table class="table table-lg">
<thead  class="table-dark">
    <tr>
      <th>NO</th>
      <th>Product_Name </th>
      <th> Price</th>
      <th>Peller_name</th>
      <th> Stoke Available</th>
      <th>Select Quantity</th>
      <th colspan="8  "></th>
    </tr>
    </thead>
  <tbody>
<% @products.each do |product| %>
 
   <%=form_with model: product, url:carts_path, method: :post do |form| %>
  <tr class="table-light"> 
   <%var=User.find(product.user_id)%>
        <td ><%=product.id%></td>  
        <td ><%= product.name %></td>
        <td ><%= product.price %></td>
        <td><%=var.name%></td>
        <% if product.quantity.nil? ||product.quantity==0%>
        <td ><strong>out of Stock</strong></td>
        <td><%= link_to 'GO TO cart',carts_path%></td>
        <%else%>
        <td><%= product.quantity %></td>
        <td ><%=form.number_field 'pro_quantity',value: 1, min: 1, max: product.quantity, step: 1%></td>
        <td ><%= link_to 'Viwe', customer_path(product) %></td>
        <td ><%=form.submit "ADD TO CART"%></td>
         <%end%>
        <td><%= form.hidden_field :product_id,value: product.id %></td>
        <td><%= form.hidden_field :sell_id,value: product.user_id %></td>
        <td><%= form.hidden_field :pro_name,value: product.name %></td>
        <td><%= form.hidden_field :pro_price,value: product.price %></td>
        <td><%= form.hidden_field :subtotal,value: 0 %></td>
      </tr>
   <%end%>
<%end%>
</tbody>
</table>
</div>
</div>
</div>
<br>
<%= button_to 'Back', customer_index_path, method: :get ,class:"btn btn-primary btn-block",style:"float:right;"%>

app/views/customer/index.html.erb
   <!--
  <div class="bg-info" style="margin:30px 380px;padding:10px 20px 5px 20px;text-align:center;">
<h1>Products</h1>
</div>-->

<div >
<%= image_tag "ban1.jpg",style:"height:600px;width:1254px; position:absolute;left:15px;top:75px;z-index:-1;"%>
<div style="margin-top:253px;">
<table class="table table-lg">
<thead  class="table-dark">
    <tr>
      <th>NO</th>
      <th>Product_Name </th>
      <th> Price</th>
      <th>Peller_name</th>
      <th> Stoke Available</th>
      <th>Select Quantity</th>
      <th colspan="8  "></th>
    </tr>
    </thead>
  <tbody>
<% @products.each do |product| %>
 
   <%=form_with model: product, url:carts_path, method: :post do |form| %>
  <tr class="table-light"> 
   <%var=User.find(product.user_id)%>
        <td ><%=product.id%></td>  
        <td ><%= product.name %></td>
        <td ><%= product.price %></td>
        <td><%=var.name%></td>
        <% if product.quantity.nil? ||product.quantity==0%>
        <td ><strong>out of Stock</strong></td>
        <td><%= link_to 'GO TO cart',carts_path%></td>
        <%else%>
        <td><%= product.quantity %></td>
        <td ><%=form.number_field 'pro_quantity',value: 1, min: 1, max: product.quantity, step: 1%></td>
        <td ><%= link_to 'Viwe', customer_path(product) %></td>
        <td ><%=form.submit "ADD TO CART"%></td>
         <%end%>
        <td><%= form.hidden_field :product_id,value: product.id %></td>
        <td><%= form.hidden_field :sell_id,value: product.user_id %></td>
        <td><%= form.hidden_field :pro_name,value: product.name %></td>
        <td><%= form.hidden_field :pro_price,value: product.price %></td>
        <td><%= form.hidden_field :subtotal,value: 0 %></td>
      </tr>
   <%end%>
<%end%>
</tbody>
</table>
</div>
</div>
</div>
<br>
<%= button_to 'Back', customer_index_path, method: :get ,class:"btn btn-primary btn-block",style:"float:right;"%>

app/views/customer/search.html.erb
   <!--
  <div class="bg-info" style="margin:30px 380px;padding:10px 20px 5px 20px;text-align:center;">
<h1>Products</h1>
</div>-->

<div >
<%= image_tag "ban1.jpg",style:"height:600px;width:1254px; position:absolute;left:15px;top:75px;z-index:-1;"%>
<div style="margin-top:253px;">
<table class="table table-lg">
<thead  class="table-dark">
    <tr>
      <th>NO</th>
      <th>Product_Name </th>
      <th> Price</th>
      <th>Peller_name</th>
      <th> Stoke Available</th>
      <th>Select Quantity</th>
      <th colspan="8  "></th>
    </tr>
    </thead>
  <tbody>
  <%count=1%>
<% @products.each do |product| %>
 
   <%=form_with model: product, url:carts_path, method: :post do |form| %>
  <tr class="table-light"> 
   <%var=User.find(product.user_id)%>
        <td ><%=count%></td>  
        <%count=count+1%>
        <td ><%= product.name %></td>
        <td ><%= product.price %></td>
        <td><%=var.name%></td>
        <% if product.quantity.nil? ||product.quantity==0%>
        <td ><strong>out of Stock</strong></td>
        <td><%= link_to 'GO TO cart',carts_path%></td>
        <%else%>
        <td><%= product.quantity %></td>
        <td ><%=form.number_field 'pro_quantity',value: 1, min: 1, max: product.quantity, step: 1%></td>
        <td ><%= link_to 'Viwe', customer_path(product) %></td>
        <td ><%=form.submit "ADD TO CART"%></td>
         <%end%>
        <td><%= form.hidden_field :product_id,value: product.id %></td>
        <td><%= form.hidden_field :sell_id,value: product.user_id %></td>
        <td><%= form.hidden_field :pro_name,value: product.name %></td>
        <td><%= form.hidden_field :pro_price,value: product.price %></td>
        <td><%= form.hidden_field :subtotal,value: 0 %></td>
      </tr>
   <%end%>
<%end%>
</tbody>
</table>
</div>
</div>
</div>
<br>
<%= button_to 'Back', customer_index_path, method: :get ,class:"btn btn-primary btn-block",style:"float:right;"%>

app/views/customer/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>


<%= link_to 'Back', customer_index_path%>
 